version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependency
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Application build
          command: npm run build

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Clear
          command: |
            ssh $SSH_USER@$SSH_HOST "rm -rf /var/www/html/*"
      - run:
          name: Deploy
          command: |
            scp -r build/* $SSH_USER@$SSH_HOST:/var/www/html

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
